Project/ShopOnline/ShopOnline/Models/Contact.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ShopOnline.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Contact
{

    public int id { get; set; }

    public Nullable<System.DateTime> dateContact { get; set; }

    public string name { get; set; }

    public string email { get; set; }

    public string message { get; set; }

}

}

Project/ShopOnline/ShopOnline/Models/InvoinceDetail.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ShopOnline.Models
{

using System;
    using System.Collections.Generic;
    
public partial class InvoinceDetail
{

    public string invoinceNo { get; set; }

    public int productId { get; set; }

    public Nullable<int> quanlityProduct { get; set; }

    public Nullable<int> unitPrice { get; set; }

    public Nullable<int> totalPrice { get; set; }

    public Nullable<int> totalDiscount { get; set; }



    public virtual Invoince Invoince { get; set; }

    public virtual Product Product { get; set; }

}

}

Project/ShopOnline/ShopOnline/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using ShopOnline.Models;

namespace shopOnline.Controllers
{
    public class HomeController : Controller
    {
        menfashionEntities db = new menfashionEntities();
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult About()
        {
            return View();
        }
        [HttpGet]
        public ActionResult Contact()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Contact(Contact contact)
        {
            contact.dateContact = DateTime.Now;
            db.Contacts.Add(contact);
            var result = db.SaveChanges();
            if (result > 0)
            {
                ViewBag.MessageSuccess = "Your message has been received by us. We will contact you as soon as possible.";
            }
            return View(contact);
        }
        public ActionResult Error()
        {
            return View();
        }    
        [HttpGet]
        public ActionResult EditProfie(string userName)
        {
            Member member = db.Members.Find(userName);
            Session["imgPath"] = member.avatar;
            return View(member);
        }            
        [HttpPost]
        public ActionResult EditProfie(Member member, HttpPostedFileBase uploadFile)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    if (uploadFile != null)
                    {
                        var fileName = Path.GetFileName(uploadFile.FileName);
                        var path = Path.Combine(Server.MapPath("~/Content/img/avatar"), fileName);

                        member.avatar = "~/Content/img/avatar/" + fileName;
                        db.Entry(member).State = EntityState.Modified;

                        string oldImgPath = Request.MapPath(Session["imgPath"].ToString()); // Lấy đường dẫn ảnh (absolute path)
                        var avatarName = Session["imgPath"].ToString(); // Lấy đường dẫn ảnh (relative path)
                        var checkAvatart = db.Members.Where(model => model.avatar == avatarName).ToList(); // Kiểm tra ảnh có trùng với avatar của member nào không

                        if (db.SaveChanges() > 0)
                        {
                            uploadFile.SaveAs(path);
                            if (System.IO.File.Exists(oldImgPath) && checkAvatart.Count < 2) // Nếu tồn tại hình trong folder và không member nào có hình này thì xóa ra khỏi folder
                            {
                                System.IO.File.Delete(oldImgPath);
                            }
                            var info = db.Members.Where(model => model.userName == member.userName).SingleOrDefault();// Lấy thông tin mới cập nhập lưu vào session
                            Session["info"] = info;
                            return RedirectToAction("Index");
                        }
                    }
                    else
                    {
                        member.avatar = Session["imgPath"].ToString();
                        db.Entry(member).State = EntityState.Modified;
                        if (db.SaveChanges() > 0)
                        {
                            var info = db.Members.Where(model => model.userName == member.userName).SingleOrDefault();// Lấy thông tin mới cập nhập lưu vào session
                            Session["info"] = info;
                            return RedirectToAction("Index");
                        }
                    }
                }
                ViewBag.roleId = new SelectList(db.Roles, "roleId", "roleName", member.roleId);
                return View(member);
            }
            catch (Exception ex)
            {
                TempData["msgEditProfieFailed"] = "Edit failed! " + ex.Message;
                return RedirectToAction("Index");
            }
        }    
        [HttpGet]
        public ActionResult ChangePassword(string userName)
        {
            Member member = db.Members.Find(userName);
            return View();
        }        
        [HttpPost]
        public ActionResult ChangePassword(Member member, FormCollection collection)
        {
            try
            {
                var CurrentPassword = collection["CurPassword"]; // Mật khẩu hiện tại
                var NewPassword = collection["NewPassword"]; // Mật khẩu mới
                //var ConfirmPassword = collection["Confirm"];

                CurrentPassword = Encryptor.MD5Hash(CurrentPassword.Trim());
                NewPassword = Encryptor.MD5Hash(NewPassword.Trim());

                var check = db.Members.Where(model => model.password == CurrentPassword && model.userName == member.userName).FirstOrDefault();
                if (check != null)
                {
                    check.password = NewPassword;
                    db.SaveChanges();
                    TempData["msgChangePassword"] = "Successfully change password!";
                    return RedirectToAction("index");
                }
                else
                {
                    ModelState.AddModelError("", "Incorrect your password!");
                    return View(member);
                }
            }
            catch (Exception ex)
            {
                TempData["msgChangePasswordFailed"] = "Edit failed! " + ex.Message;
                return RedirectToAction("Index");
            }
        }
        [HttpGet]
        public ActionResult MyOrder(string userName)
        {
            var orders = db.Invoinces.OrderByDescending(model => model.dateOrder).Where(model => model.userName == userName).ToList();
            return View(orders);
        }
        [HttpGet]
        public ActionResult InvoinceDetail(string invoinceNo)
        {
            var detail = db.InvoinceDetails.Where(model => model.invoinceNo == invoinceNo).Include(model => model.Product).ToList();
            var infor = db.Invoinces.Where(model => model.invoinceNo == invoinceNo).Include(model => model.Member).FirstOrDefault();
            ViewBag.invoinceNo = invoinceNo;
            Session["information"] = infor;

            return View(detail);
        }
        public ActionResult Delete(string id)
        {
            List<InvoinceDetail> ctdh = db.InvoinceDetails.Where(model => model.invoinceNo == id).ToList();
            foreach (var i in ctdh)
            {
                db.InvoinceDetails.Remove(i);
            }
            db.SaveChanges();
            Invoince invoince = db.Invoinces.Find(id);
            db.Invoinces.Remove(invoince);
            TempData["msgDeleteOrder"] = "Successfully delete order!";
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        public PartialViewResult ProductHome()
        {
            var list = db.Products.OrderByDescending(model => model.dateCreate).Take(8).ToList();
            return PartialView(list);
        }
        public PartialViewResult BlogHome()
        {
            var list = db.Articles.OrderByDescending(model => model.publicDate).Take(3).ToList();
            return PartialView(list);
        }
    }
}

Project/ShopOnline/ShopOnline/Controllers/ShopController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ShopOnline.Models;
using PagedList;

namespace shopOnline.Controllers
{
    public class ShopController : Controller
    {
        menfashionEntities db = new menfashionEntities();
        // GET: Shop
        public ActionResult ProductList()
        {
            return View();
        }
        public PartialViewResult ListItem(string brand,int? categories,int? page, string searching) // Show product
        {
            var pageNumber = page ?? 1;
            var pageSize = 9;
            if(searching != null)
            {
                ViewBag.categories = categories;
                var list = db.Products.Where(model => model.productName.Contains(searching) || searching == null && model.status == true).OrderByDescending(model => model.dateCreate).ToPagedList(pageNumber, pageSize);
                return PartialView(list);
            }
            else
            {
                if (brand != null && categories == null)
                {
                    ViewBag.categories = categories;
                    var list = db.Products.OrderByDescending(model => model.dateCreate).Where(model => model.brand == brand && model.status == true).ToPagedList(pageNumber, pageSize);
                    return PartialView(list);
                }
                else if (brand == null && categories != null)
                {
                    ViewBag.categories = categories;
                    var list = db.Products.OrderByDescending(model => model.dateCreate).Where(model => model.categoryId == categories && model.status == true).ToPagedList(pageNumber, pageSize);
                    return PartialView(list);
                }
                else
                {
                    var list = db.Products.OrderByDescending(model => model.dateCreate).Where(model => model.status == true).ToPagedList(pageNumber, pageSize);
                    return PartialView(list);
                }
            }
        }
        public PartialViewResult Categories() // List categories
        {
            var list = db.ProductCategories.ToList();
            return PartialView(list);
        }
        public PartialViewResult Brand() // List brand
        {
            List<String> brand = new List<string>();
            foreach (Product i in this.db.Products)
            {
                if (!brand.Contains(i.brand.Trim()))
                    brand.Add(i.brand.Trim());
            }
            return PartialView(brand);
        }        
        public PartialViewResult RelationProduct(int? category) // List brand
        {
            var categories = db.Products.Where(model => model.categoryId == category).Take(4).ToList();
            return PartialView(categories);
        }

        public ActionResult ProductDetail(int? id, int? category)
        {
            if (id == null)
            {
                return RedirectToAction("Error", "Home");
            }
            var detail = db.Products.Where(model => model.productId == id).Single();
            ViewBag.NewPrice = detail.price - ((detail.price * detail.discount) / 100);
            if (detail == null)
            {
                return RedirectToAction("Error", "Home");
            }
            return View(detail);
        }
    }
}

Project/ShopOnline/ShopOnline/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
    Layout = "~/Views/Shared/_LayoutPublicPage.cshtml";
}
<script>
    var obj = document.querySelector(".navlist li:nth-child(1)");
    var obj2 = document.querySelector(".navlist li:nth-of-type(4)");
    obj.classList.remove("active");
    obj2.classList.add("active");
</script>

<!-- Breadcrumb Section Begin -->
<section class="breadcrumb-option">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <div class="breadcrumb__text">
                    <h4>About Us</h4>
                    <div class="breadcrumb__links">
                        <a href="~/Home/Index">Home</a>
                        <span>About Us</span>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
<!-- Breadcrumb Section End -->
<!-- About Section Begin -->
<section class="about spad">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <div class="about__pic">
                    <img src="~/Content/img/about/about-us.jpg" alt="">
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-lg-4 col-md-4 col-sm-6">
                <div class="about__item">
                    <h4>Who We Are ?</h4>
                    <p>
                        Contextual advertising programs sometimes have strict policies that need to be adhered too.
                        Let’s take Google as an example.
                    </p>
                </div>
            </div>
            <div class="col-lg-4 col-md-4 col-sm-6">
                <div class="about__item">
                    <h4>Who We Do ?</h4>
                    <p>
                        In this digital generation where information can be easily obtained within seconds, business
                        cards still have retained their importance.
                    </p>
                </div>
            </div>
            <div class="col-lg-4 col-md-4 col-sm-6">
                <div class="about__item">
                    <h4>Why Choose Us</h4>
                    <p>
                        A two or three storey house is the ideal way to maximise the piece of earth on which our home
                        sits, but for older or infirm people.
                    </p>
                </div>
            </div>
        </div>
    </div>
</section>
<!-- About Section End -->
<!-- Testimonial Section Begin -->
<section class="testimonial">
    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-6 p-0">
                <div class="testimonial__text">
                    <span class="icon_quotations"></span>
                    <p>
                        “Going out after work? Take your butane curling iron with you to the office, heat it up,
                        style your hair before you leave the office and you won’t have to make a trip back home.”
                    </p>
                    <div class="testimonial__author">
                        <div class="testimonial__author__pic">
                            <img src="~/Content/img/about/testimonial-author.jpg" alt="">
                        </div>
                        <div class="testimonial__author__text">
                            <h5>Augusta Schultz</h5>
                            <p>Fashion Design</p>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-lg-6 p-0">
                <div class="testimonial__pic set-bg" data-setbg=@Url.Content("~/Content/img/about/testimonial-pic.jpg")></div>
            </div>
        </div>
    </div>
</section>
<!-- Testimonial Section End -->
<!-- Counter Section Begin -->
<section class="counter spad">
    <div class="container">
        <div class="row">
            <div class="col-lg-3 col-md-6 col-sm-6">
                <div class="counter__item">
                    <div class="counter__item__number">
                        <h2 class="cn_num">102</h2>
                    </div>
                    <span>Our <br />Clients</span>
                </div>
            </div>
            <div class="col-lg-3 col-md-6 col-sm-6">
                <div class="counter__item">
                    <div class="counter__item__number">
                        <h2 class="cn_num">30</h2>
                    </div>
                    <span>Total <br />Categories</span>
                </div>
            </div>
            <div class="col-lg-3 col-md-6 col-sm-6">
                <div class="counter__item">
                    <div class="counter__item__number">
                        <h2 class="cn_num">102</h2>
                    </div>
                    <span>In <br />Country</span>
                </div>
            </div>
            <div class="col-lg-3 col-md-6 col-sm-6">
                <div class="counter__item">
                    <div class="counter__item__number">
                        <h2 class="cn_num">98</h2>
                        <strong>%</strong>
                    </div>
                    <span>Happy <br />Customer</span>
                </div>
            </div>
        </div>
    </div>
</section>
<!-- Counter Section End -->
<!-- Team Section Begin -->
<section class="team spad">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <div class="section-title">
                    <span>Our Team</span>
                    <h2>Meet Our Team</h2>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-lg-3 col-md-6 col-sm-6">
                <div class="team__item">
                    <img src="~/Content/img/about/team-1.jpg" alt="">
                    <h4>John Smith</h4>
                    <span>Fashion Design</span>
                </div>
            </div>
            <div class="col-lg-3 col-md-6 col-sm-6">
                <div class="team__item">
                    <img src="~/Content/img/about/team-2.jpg" alt="">
                    <h4>Christine Wise</h4>
                    <span>C.E.O</span>
                </div>
            </div>
            <div class="col-lg-3 col-md-6 col-sm-6">
                <div class="team__item">
                    <img src="~/Content/img/about/team-3.jpg" alt="">
                    <h4>Sean Robbins</h4>
                    <span>Manager</span>
                </div>
            </div>
            <div class="col-lg-3 col-md-6 col-sm-6">
                <div class="team__item">
                    <img src="~/Content/img/about/team-4.jpg" alt="">
                    <h4>Lucy Myers</h4>
                    <span>Delivery</span>
                </div>
            </div>
        </div>
    </div>
</section>
<!-- Team Section End -->
<!-- Client Section Begin -->
<section class="clients spad">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <div class="section-title">
                    <span>Partner</span>
                    <h2>Happy Clients</h2>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-lg-3 col-md-4 col-sm-4 col-6">
                <a href="#" class="client__item"><img src="~/Content/img/clients/client-1.png" alt=""></a>
            </div>
            <div class="col-lg-3 col-md-4 col-sm-4 col-6">
                <a href="#" class="client__item"><img src="~/Content/img/clients/client-2.png" alt=""></a>
            </div>
            <div class="col-lg-3 col-md-4 col-sm-4 col-6">
                <a href="#" class="client__item"><img src="~/Content/img/clients/client-3.png" alt=""></a>
            </div>
            <div class="col-lg-3 col-md-4 col-sm-4 col-6">
                <a href="#" class="client__item"><img src="~/Content/img/clients/client-4.png" alt=""></a>
            </div>
            <div class="col-lg-3 col-md-4 col-sm-4 col-6">
                <a href="#" class="client__item"><img src="~/Content/img/clients/client-5.png" alt=""></a>
            </div>
            <div class="col-lg-3 col-md-4 col-sm-4 col-6">
                <a href="#" class="client__item"><img src="~/Content/img/clients/client-6.png" alt=""></a>
            </div>
            <div class="col-lg-3 col-md-4 col-sm-4 col-6">
                <a href="#" class="client__item"><img src="~/Content/img/clients/client-7.png" alt=""></a>
            </div>
            <div class="col-lg-3 col-md-4 col-sm-4 col-6">
                <a href="#" class="client__item"><img src="~/Content/img/clients/client-8.png" alt=""></a>
            </div>
        </div>
    </div>
</section>
<!-- Client Section End -->

Project/ShopOnline/ShopOnline/Views/Home/BlogHome.cshtml
@using ShopOnline.Models
@model List<Article>
<div class="row">
    @foreach (var i in Model)
    {
    <div class="col-lg-4 col-md-6 col-sm-6">
        <div class="blog__item">
            <div class="blog__item__pic set-bg" data-setbg=@Url.Content(""+@i.image)></div>
            <div class="blog__item__text">
                <span><img src="~/Content/img/icon/calendar.png" alt=""> @i.publicDate</span>
                <h5>@i.title</h5>
                <a href="@Url.Action("ArticleDetail","Article",new { id = i.articleId})">Read More</a>
            </div>
        </div>
    </div>
    }

</div>

Project/ShopOnline/ShopOnline/Views/Home/ChangePassword.cshtml
@model ShopOnline.Models.Member
@{
    ViewBag.Title = "ChangePassword";
    Layout = "~/Views/Shared/_LayoutPublicPage.cshtml";
}

<div class="container">
    <div class="singinBx">

        @using (Html.BeginForm("ChangePassword", "Home", FormMethod.Post, new { @id = "form-1", @enctype = "multipart/form-data" }))
        {
            <div class="form-group">
                <div class="col-md-10" style="margin: auto">
                    <h3>Change password</h3>
                </div>
            </div>
            @Html.AntiForgeryToken()
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })

            @Html.HiddenFor(model => model.dateOfJoin)
            @Html.HiddenFor(model => model.status)
            @Html.HiddenFor(model => model.roleId)
            @Html.HiddenFor(model => model.userName)
            @Html.HiddenFor(model => model.firstName)
            @Html.HiddenFor(model => model.lastName)
            @Html.HiddenFor(model => model.email)
            @Html.HiddenFor(model => model.identityNumber)
            @Html.HiddenFor(model => model.phone)
            @Html.HiddenFor(model => model.address)
            @Html.HiddenFor(model => model.birthday)
            @Html.HiddenFor(model => model.avatar)


            <div class="form-group">
                @Html.EditorFor(model => model.userName, new { htmlAttributes = new { @class = "form-control", @id = "userName", @type = "hidden" } })
            </div>


            <div class="form-group">
                <input type="password" class="form-control" id="current-password" name="CurPassword" placeholder="Current password" />
                <span class="form-message"></span>
            </div>
            <div class="form-group">
                <input type="password" class="form-control" id="new-password" name="NewPassword" placeholder="New password" />
                <span class="form-message"></span>
            </div>
            <div class="form-group">
                <input type="password" class="form-control" id="password_confirmation" name="Confirm" placeholder="Confirm password" />
                <span class="form-message"></span>
            </div>
            <div class="form-group">
                <button type="submit" class="btn-submitForm">Submit</button>
            </div>
            @*<div class="form-actions">
                <div class="text-left">
                    <button type="submit" class="btn btn-info">Submit</button>
                    <button type="reset" class="btn btn-dark">Reset</button>
                </div>
            </div>*@
        }

    </div>
</div>

<script src="~/Content/js/validator.js"></script>
<script>
    Validator({
        form: '#form-1',
        formGroupSelector: '.form-group',
        errorSelector: '.form-message',
        rules: [

            Validator.isRequired('#current-password'),
            Validator.minLength('#new-password', 6),
            Validator.isConfirmed('#password_confirmation', function () {
                return document.querySelector('#form-1 #new-password').value;
            }, 'Passwords must match')
        ],
    });
</script>

Project/ShopOnline/ShopOnline/Views/Home/ProductHome.cshtml
@using ShopOnline.Models
@model List<Product>
<div class="row product__filter">
    @foreach (var i in Model)
    {
        if (i.discount > 0)
        {
            <div class="col-lg-3 col-md-6 col-sm-6 col-md-6 col-sm-6 mix new-arrivals">
                <div class="product__item">
                    <div class="product__item__pic set-bg" data-setbg=@Url.Content(""+i.image)>
                        @if (i.discount != 0)
                        {
                            <span class="label">Sale</span>
                        }
                        <ul class="product__hover">
                            <li><a href="#"><img src="~/Content/img/icon/heart.png" alt=""></a></li>
                            <li><a href="#"><img src="~/Content/img/icon/compare.png" alt=""> <span>Compare</span></a></li>
                            <li><a href="#"><img src="~/Content/img/icon/search.png" alt=""></a></li>
                        </ul>
                    </div>
                    <div class="product__item__text">
                        <h6><a href="@Url.Action("ProductDetail", "Shop", new { id = i.productId ,category = i.categoryId})" class="nameProduct">@i.productName</a></h6>
                        <a href="@Url.Action("AddToCart", "Cart", new { id = i.productId, @strURL = Request.Url.ToString() })" class="add-cart">+ Add To Cart</a>
                        <div class="rating">
                            <i class="fa fa-star-o"></i>
                            <i class="fa fa-star-o"></i>
                            <i class="fa fa-star-o"></i>
                            <i class="fa fa-star-o"></i>
                            <i class="fa fa-star-o"></i>
                        </div>
                        <h5>
                            @if (i.discount != 0)
                            {
                                 var giaDaGiam = i.price - ((i.price * i.discount) / 100);
                                 <span>$</span>@giaDaGiam
                                 <span class="discount-price">@i.price</span>
                            }
                            else
                            {
                                @i.price
                            }
                        </h5>
                        <div class="product__color__select">
                            <label for="pc-1">
                                <input type="radio" id="pc-1">
                            </label>
                            <label class="active black" for="pc-2">
                                <input type="radio" id="pc-2">
                            </label>
                            <label class="grey" for="pc-3">
                                <input type="radio" id="pc-3">
                            </label>
                        </div>
                    </div>
                </div>
            </div> 
        }
        else
        {
            <div class="col-lg-3 col-md-6 col-sm-6 col-md-6 col-sm-6 mix hot-sales">
                <div class="product__item">
                    <div class="product__item__pic set-bg" data-setbg=@Url.Content(""+i.image)>
                        @if (i.discount != 0)
                         {
                            <span class="label">Sale</span>
                         }
                        <ul class="product__hover">
                            <li><a href="#"><img src="~/Content/img/icon/heart.png" alt=""></a></li>
                            <li><a href="#"><img src="~/Content/img/icon/compare.png" alt=""> <span>Compare</span></a></li>
                            <li><a href="#"><img src="~/Content/img/icon/search.png" alt=""></a></li>
                        </ul>
                    </div>
                    <div class="product__item__text">
                        <h6><a href="@Url.Action("ProductDetail", "Shop", new { id = i.productId ,category = i.categoryId})" class="nameProduct">@i.productName</a></h6>
                        <a href="@Url.Action("AddToCart", "Cart", new { id = i.productId, @strURL = Request.Url.ToString() })" class="add-cart">+ Add To Cart</a>
                        <div class="rating">
                            <i class="fa fa-star"></i>
                            <i class="fa fa-star"></i>
                            <i class="fa fa-star"></i>
                            <i class="fa fa-star"></i>
                            <i class="fa fa-star-o"></i>
                        </div>
                        <h5>
                            $@{ var price = i.price - ((i.price * i.discount) / 100); }@price @if (i.discount != 0)
                            {<span>@i.price</span>}
                        </h5>
                        <div class="product__color__select">
                            <label for="pc-1">
                                <input type="radio" id="pc-1">
                            </label>
                            <label class="active black" for="pc-2">
                                <input type="radio" id="pc-2">
                            </label>
                            <label class="grey" for="pc-3">
                                <input type="radio" id="pc-3">
                            </label>
                        </div>
                    </div>
                </div>
            </div>
        }
     }
</div>        