Project/ShopOnline/ShopOnline/Areas/Admin/Controllers/CRUDmemberController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ShopOnline.Models;
using System.IO;
using PagedList;
using PagedList.Mvc;
using System.Web.Security;

namespace ShopOnline.Areas.Admin.Controllers
{
    [Authorize]
    public class CRUDmemberController : Controller
    {
        menfashionEntities db = new menfashionEntities();
        public ActionResult Index(int? page, string searching)
        {
            var pageNumber = page ?? 1;
            var pageSize = 10;
            var member = db.Members.Where(model => model.userName.Contains(searching) || searching == null).OrderByDescending(model => model.dateOfJoin).Include(model => model.Role).ToPagedList(pageNumber, pageSize);
            return View(member);
        }
        //CREATE
        [HttpGet]
        public ActionResult Create()
        {
            ViewBag.roleId = new SelectList(db.Roles, "roleId", "roleName");
            return View();
        }
        [HttpPost]
        public ActionResult Create(Member member, HttpPostedFileBase uploadFile)
        {
            try
            {
                var username = member.userName.Trim();
                // Lấy tên đăng nhập đã nhập vào kiểm tra có trùng 
                var check = db.Members.SingleOrDefault(model => model.userName == username);
                // Xử lí ảnh
                var fileName = Path.GetFileName(uploadFile.FileName);
                var path = Path.Combine(Server.MapPath("~/Content/img/avatar"), fileName);
                string extension = Path.GetExtension(uploadFile.FileName);

                if (extension.ToLower() == ".jpg" || extension.ToLower() == ".jpeg" || extension.ToLower() == ".png")
                {
                    if (check != null)
                    {
                        ModelState.AddModelError("", "Username already exists");
                    }
                    else
                    {
                        if (uploadFile == null)
                        {
                            ModelState.AddModelError("", "Error while file uploading.");
                        }
                        else
                        {
                            member.firstName = member.firstName.Trim();
                            member.lastName = member.lastName.Trim();
                            member.email = member.email.Trim();
                            member.address = member.address.Trim();
                            member.phone = member.phone.Trim();
                            member.identityNumber = member.identityNumber.Trim();
                            member.avatar = "~/Content/img/avatar/" + fileName;
                            member.dateOfJoin = DateTime.Now;
                            member.status = true;
                            member.password = Encryptor.MD5Hash(member.password);
                            db.Members.Add(member);
                            if (db.SaveChanges() > 0)
                            {
                                uploadFile.SaveAs(path);
                                ModelState.Clear();
                                TempData["msgCreate"] = "Successfully create a new member!";
                                return RedirectToAction("Index");
                            }
                        }
                    }
                }
                else
                {
                    ModelState.AddModelError("", "Invalid File Type");
                }

                ViewBag.roleId = new SelectList(db.Roles, "roleId", "roleName", member.roleId);
                return View(member);
            }
            catch(Exception ex)
            {
                TempData["msgCreatefailed"] = "Create failed! " + ex.Message;
                return RedirectToAction("Create");
            }
        }

        // EDIT
        [HttpGet]
        public ActionResult Edit(string userName)
        {
            Member member = db.Members.Find(userName);
            Session["imgPath"] = member.avatar;
            ViewBag.roleId = new SelectList(db.Roles, "roleId", "roleName", member.roleId);
            return View(member);
        }
        [HttpPost]
        public ActionResult Edit(Member member, HttpPostedFileBase uploadFile)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    if (uploadFile != null)
                    {
                        var fileName = Path.GetFileName(uploadFile.FileName);
                        var path = Path.Combine(Server.MapPath("~/Content/img/avatar"), fileName);
                        member.avatar = "~/Content/img/avatar/" + fileName;
                        db.Entry(member).State = EntityState.Modified;
                        string oldImgPath = Request.MapPath(Session["imgPath"].ToString());
                        if (db.SaveChanges() > 0)
                        {
                            TempData["msgEdit"] = "Successfully edited!";
                            uploadFile.SaveAs(path);
                            if (System.IO.File.Exists(oldImgPath))
                            {
                                System.IO.File.Delete(oldImgPath);
                            }
                        }
                        return RedirectToAction("Index");
                    }
                    else
                    {
                        member.avatar = Session["imgPath"].ToString();
                        db.Entry(member).State = EntityState.Modified;
                        if (db.SaveChanges() > 0)
                        {
                            TempData["msgEdit"] = "Successfully edited!";
                            return RedirectToAction("index");
                        }
                    }
                }
                ViewBag.roleId = new SelectList(db.Roles, "roleId", "roleName", member.roleId);
                return View(member);
            }
            catch(Exception ex)
            {
                TempData["msgEditFailed"] = "Edit failed! " + ex.Message;
                return RedirectToAction("Index");
            }
        }

        // DELETE
        public ActionResult Delete(string userName)
        {
            try
            {
                Member member = db.Members.Find(userName);
                var checkArticle = db.Articles.FirstOrDefault(model => model.userName == userName);
                var checkInvoice = db.Invoinces.FirstOrDefault(model => model.userName == userName);
                var checkProduct = db.Products.FirstOrDefault(model => model.userName == userName);
                string currentImg = Request.MapPath(member.avatar);
                // Kiểm tra xem  tài khoản có trong bảng Article, bảng Invoice hoặc bảng Product không
                if (checkArticle != null || checkInvoice != null || checkProduct != null) // Nếu có 1 trong 3 giá trị thì không cho xóa
                {
                    TempData["msgDeleteFailed"] = "Can't delete this! ";
                    return RedirectToAction("Index");
                }
                else
                {
                    // Kiểm tra xem tài khoản đăng nhập hiện tại có trùng với tài khoản xóa hay không
                    if (Session["userNameAdmin"].ToString() == member.userName) // Nếu trùng thì xóa tài khoản và đăng xuất, chuyển về trang đăng nhập
                    {
                        var avatarName = member.avatar.ToString(); // Lấy đường dẫn ảnh (relative path)
                        var checkAvatart = db.Members.Where(model => model.avatar == avatarName).ToList(); // Kiểm tra ảnh có trùng với avatar của member nào không
                        if (System.IO.File.Exists(currentImg) && checkAvatart.Count < 2)
                        {
                            System.IO.File.Delete(currentImg);
                        }
                        db.Members.Remove(member);
                        db.SaveChanges();
                        FormsAuthentication.SignOut();
                        return RedirectToAction("Login", "LoginMember");
                    }
                    else
                    {
                        var avatarName = member.avatar.ToString(); // Lấy đường dẫn ảnh (relative path)
                        var checkAvatart = db.Members.Where(model => model.avatar == avatarName).ToList(); // Kiểm tra ảnh có trùng với avatar của member nào không
                        if (System.IO.File.Exists(currentImg) && checkAvatart.Count < 2)
                        {
                            System.IO.File.Delete(currentImg);
                        }
                        db.Members.Remove(member);
                        db.SaveChanges();
                        return RedirectToAction("Index");
                    }
                }
            }
            catch (Exception ex)
            {
                TempData["msgDeleteFailed"] = "Can't delete this! " + ex.Message;
                return RedirectToAction("Index");
            }
        }
    }
}

Project/ShopOnline/ShopOnline/Areas/Admin/Views/CRUDmember/Create.cshtml
@{
    ViewBag.Title = "Create";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutDashBoard.cshtml";
}

<div class="page-breadcrumb">
    <div class="row">
        <div class="col-7 align-self-center">
            <h4 class="page-title text-truncate text-dark font-weight-medium mb-1">Member</h4>
            <div class="d-flex align-items-center">
                <nav aria-label="breadcrumb">
                    <ol class="breadcrumb m-0 p-0">
                        <li class="breadcrumb-item"><a href="~/Admin/DashBoard/Index" class="text-muted">Home</a></li>
                        <li class="breadcrumb-item text-muted active" aria-current="page">Create member</li>
                    </ol>
                </nav>
            </div>
        </div>
        <div class="col-5 align-self-center">
            <div class="customize-input float-right">
                <select class="custom-select custom-select-set form-control bg-white border-0 custom-shadow custom-radius">
                    <option selected>Aug 19</option>
                    <option value="1">July 19</option>
                    <option value="2">Jun 19</option>
                </select>
            </div>
        </div>
    </div>
</div>
<div class="container-fluid">
    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-body">
                    <h3 class="card-title">Create member</h3>
                    @if (TempData["msgCreatefailed"] != null)
                    {
                        <div class="alert alert-danger alert-dismissible bg-danger text-white border-0 fade show" role="alert">
                            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                <span aria-hidden="true">×</span>
                            </button>
                            @TempData["msgCreatefailed"]
                        </div>
                    }
                    @using (Html.BeginForm("Create", "CRUDmember", FormMethod.Post, new { @id = "form-1", @enctype = "multipart/form-data" }))
                    {
                        @Html.AntiForgeryToken()
                        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

                        <div class="form-body">
                            <div class="row">
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label for="userName">Username</label>
                                        <input type="text" class="form-control" name="userName" id="userName" />
                                        <span class="form-message"></span>
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label for="password">Password</label>
                                        <input type="password" class="form-control" name="password" id="password" />
                                        <span class="form-message"></span>
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label for="firstName">First name</label>
                                        <input type="text" class="form-control" name="firstName" id="firstName" />
                                        <span class="form-message"></span>
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label for="lastName">Last name</label>
                                        <input type="text" class="form-control" name="lastName" id="lastName" />
                                        <span class="form-message"></span>
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label for="address">Address</label>
                                        <input type="text" class="form-control" name="address" id="address" />
                                        <span class="form-message"></span>
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label for="email">Email</label>
                                        <input type="email" class="form-control" name="email" id="email" />
                                        <span class="form-message"></span>
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label for="phone">Phone</label>
                                        <input type="number" class="form-control" name="phone" id="phone" />
                                        <span class="form-message"></span>
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label for="identityNumber">Identity number</label>
                                        <input type="number" class="form-control" name="identityNumber" id="identityNumber" />
                                        <span class="form-message"></span>
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label for="birthday">Birthday</label>
                                        <input type="date" class="form-control" name="birthday" id="birthday" />
                                        <span class="form-message"></span>
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label for="">Role</label>
                                        @Html.DropDownList("roleId", null, htmlAttributes: new { @class = "form-control" })
                                        <span class="form-message"></span>
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-12">
                                    <div class="form-group">
                                        <label for="image">Image</label>
                                        <img id="file-ip-1-preview" style="margin-bottom: 10px" />
                                        <input type="file" name="uploadFile" class="form-control-file" id="image" onchange="showPreview(event);" />
                                        <span class="form-message"></span>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="form-actions">
                            <div class="text-right">
                                <button type="submit" class="btn btn-info">Submit</button>
                                <button type="reset" class="btn btn-dark">Reset</button>
                            </div>
                        </div>
                    }
                </div>
            </div>
        </div>
    </div>
</div>
<script src="~/Content/js/validator.js"></script>
<script>
    Validator({
        form: '#form-1',
        formGroupSelector: '.form-group',
        errorSelector: '.form-message',
        rules: [
            Validator.isRequired('#userName'),
            Validator.isRequired('#password'),
            Validator.isRequired('#firstName'),
            Validator.isRequired('#lastName'),
            Validator.isRequired('#email'),
            Validator.isEmail('#email'),
            Validator.isRequired('#birthday'),
            Validator.isRequired('#identityNumber'),
            Validator.isRequired('#phone'),
            Validator.isRequired('#address'),
            Validator.isRequired('#image'),
        ],
    });

    function showPreview(event) {
        if (event.target.files.length > 0) {
            var src = URL.createObjectURL(event.target.files[0]);
            var preview = document.getElementById("file-ip-1-preview");
            preview.src = src;
            preview.style.display = "block";
            preview.style.height = "200px";
        }
    }
</script>

Project/ShopOnline/ShopOnline/Areas/Admin/Views/CRUDmember/Edit.cshtml
@model ShopOnline.Models.Member
@{
    ViewBag.Title = "Edit";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutDashBoard.cshtml";
}

<div class="page-breadcrumb">
    <div class="row">
        <div class="col-7 align-self-center">
            <h4 class="page-title text-truncate text-dark font-weight-medium mb-1">Edit member</h4>
            <div class="d-flex align-items-center">
                <nav aria-label="breadcrumb">
                    <ol class="breadcrumb m-0 p-0">
                        <li class="breadcrumb-item"><a href="~/Admin/CRUDmember/Index" class="text-muted">Member list</a></li>
                        <li class="breadcrumb-item text-muted active" aria-current="page">Edit</li>
                    </ol>
                </nav>
            </div>
        </div>
        <div class="col-5 align-self-center">
            <div class="customize-input float-right">
                <select class="custom-select custom-select-set form-control bg-white border-0 custom-shadow custom-radius">
                    <option selected>Aug 19</option>
                    <option value="1">July 19</option>
                    <option value="2">Jun 19</option>
                </select>
            </div>
        </div>
    </div>
</div>

<div class="container-fluid">
    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-body">
                    <h3 class="card-title">Edit member</h3>
                    @using (Html.BeginForm("Edit", "CRUDmember", FormMethod.Post, new { @id = "form-1", @enctype = "multipart/form-data" }))
                    {
                        @Html.AntiForgeryToken()
                        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                        <div class="form-body">
                            @Html.HiddenFor(model => model.dateOfJoin)
                            @Html.HiddenFor(model => model.password)
                            <div class="row">
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label for="userName">Username</label>
                                        @Html.EditorFor(model => model.userName, new { htmlAttributes = new { @class = "form-control", @id = "userName", @readonly = "readonly" } })
                                        <span class="form-message"></span>
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label for="email">Email</label>
                                        @Html.EditorFor(model => model.email, new { htmlAttributes = new { @class = "form-control", @id = "email" } })
                                        <span class="form-message"></span>
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label for="firstName">FirstName</label>
                                        @Html.EditorFor(model => model.firstName, new { htmlAttributes = new { @class = "form-control", @id = "firstName" } })
                                        <span class="form-message"></span>
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label for="lastName">LastName</label>
                                        @Html.EditorFor(model => model.lastName, new { htmlAttributes = new { @class = "form-control", @id = "lastName" } })
                                        <span class="form-message"></span>
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label for="address">Address</label>
                                        @Html.EditorFor(model => model.address, new { htmlAttributes = new { @class = "form-control", @id = "address" } })
                                        <span class="form-message"></span>
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label for="birthday">Birthday</label>
                                        @*@Html.EditorFor(model => model.birthday, new { htmlAttributes = new { @class = "form-control", @id = "birthday", @type = "date", @Value = Model.birthday != null ? Model.birthday.Value.Date.ToString("yyyy-MM-dd") : null } })*@
                                        @Html.EditorFor(model => model.birthday, new { htmlAttributes = new { @class = "form-control", @id = "birthday", @Value = @Model.birthday.Value.Date.ToString("yyyy/MM/dd") } })
                                        <span class="form-message"></span>
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label for="identityNumber">Identity number</label>
                                        @Html.EditorFor(model => model.identityNumber, new { htmlAttributes = new { @class = "form-control", @id = "identityNumber", @type = "number" } })
                                        <span class="form-message"></span>
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label for="phone">Phone</label>
                                        @Html.EditorFor(model => model.phone, new { htmlAttributes = new { @class = "form-control", @id = "phone", @type = "number" } })
                                        <span class="form-message"></span>
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label for="productName">Is checked</label>
                                        @Html.EditorFor(model => model.status, new { htmlAttributes = new { @class = "form-control", @id = "status" } })
                                        <span class="form-message"></span>
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label for="productName">Role</label>
                                        @Html.DropDownList("roleId", null, htmlAttributes: new { @class = "form-control" })
                                        <span class="form-message"></span>
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-12">
                                    <div class="form-group">
                                        <label for="">Image</label>
                                        <img src=@Url.Content(Model.avatar) class="img-thumbnail" width="20%" style="display:block; margin-bottom:10px" id="imagePreview" />
                                        <input type="file" name="uploadFile" class="form-control-file" id="image" accept="image/jpeg, image/png" onclick="defaultBtnActive()" />
                                        <span class="form-message"></span>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="form-actions">
                            <div class="text-right">
                                <button type="submit" class="btn waves-effect waves-light btn-success">Edit</button>
                                <a href="~/Admin/CRUDmember/Index" class="btn btn-info">Back to list</a>
                            </div>
                        </div>
                    }
                </div>
            </div>
        </div>
    </div>
</div>
<script src="~/Content/js/validator.js"></script>
<script>
    Validator({
        form: '#form-1',
        formGroupSelector: '.form-group',
        errorSelector: '.form-message',
        rules: [
            Validator.isRequired('#firstName'),
            Validator.isRequired('#lastName'),
            Validator.isEmail('#email'),
            Validator.isDate('#birthday'),
            Validator.isRequired('#identityNumber'),
            Validator.isRequired('#phone'),
            Validator.isRequired('#address'),
        ],
    });
</script>
<script>
    const inputImg = document.querySelector("#image");
    const img = document.querySelector("#imagePreview");

    function defaultBtnActive() {
        inputImg.change();
    }
    inputImg.addEventListener("change", function () {
        const file = this.files[0];
        if (file) {
            const reader = new FileReader();
            reader.onload = function () {
                const result = reader.result;
                img.src = result;
            }
            reader.readAsDataURL(file);
        }
    });
</script>